### ISSUE TITLE
vBarInternal is not working

### ISSUE THREAD

**Issue by kirill001** [luiguild/v-bar#19]
```
<v-bar wrapper="scrolled-container"
               vBar="v-bar"
               vBarInternal="v-bar-internal">...</v-bar>
.v-bar {
        background: none !important;
}

.v-bar-internal {
        background: red !important;
}
```
This code is not working. And unfortunately you didn't add examples how to customize it.

**Comment by luiguild** [comment]
Hi @kirill001! Thanks to want use V-Bar! Could you provide more of your code? If you access the V-Bar demo you will see that this attribute works fine... https://luiguild.github.io/v-bar/
