### ISSUE TITLE
Scrollbar top snaps to cursor

### ISSUE THREAD

**Issue by robbeman** [luiguild/v-bar#6]
In the demo page the top of the scrollbar snaps to the cursor position when you grab it. The scrollbar should be given a negative offset according to the position where it has been grabbed.

**Comment by luiguild** [comment]
Hi @robbeman! Thank you to create an issue an report this behavior. This is an known issue since I created VBar... You can help me with this? 😄

**Comment by robbeman** [comment]
I won't make the change in the code directly (don't want to spend too much time here, sorry), but I can make these quick suggestions:
```
        startDragY (e) {
            e.preventDefault()
            e.stopPropagation()
            e = e.changedTouches ? e.changedTouches[0] : e

            // this should get the top offset of the scrollbar relative to the document
            let elementOffset = this.verticalBar.elm.offsetTop
            // and get the difference between the element offset and the scrollbar position
            let offset = e.clientY - elementOffset

            this.dragging = {
                enable: true,
                axis: 'Y',
                offset: offset
            }
        },
```

And then modify the getCoordinates method to something like this:
```
...
            } else if (axis === 'Y') {
                sizeWrapper = this.wrapperObj.scrollHeight
                sizeBar = this.bars.vertical.size
                sizeContainer = this.container.scrollHeight
                offsetContainer = this.container.elm.offsetTop

                // calculate the position by adding the offset we got in the drag start method
                // you could pass the offset through with function arguments, if that suits you more
                clientDirection = e.clientY - this.dragging.offset
            }
...
```

Note that this is untested, so you might have to make some changes, but I feel like this could do the trick. And the same thing needs to be done for the X-axis off course.

**Comment by luiguild** [comment]
Nice @robbeman! I made these changes and it's worked nicely! I will publish in the next release...
