### ISSUE TITLE
Why padding to all childs?

### ISSUE THREAD

**Issue by breadlesscode** [luiguild/v-bar#8]
Why are all childs with padding?

https://github.com/luiguild/v-bar/blob/master/src/components/v-bar.vue#L21-L22

**Comment by luiguild** [comment]
Hi @breadlesscode! Thanks to inspect the V-Bar code! 😃 
It's for 'all childs', but as I enabled 'scoped attribute', so in this case it's only applied on slot's child... 
The ':first' pseudo element or others techniques don't worked with slots... 
But, you have any better idea?
